# Generated by Django 2.1 on 2018-12-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181224_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('is_courier', 'Разрешения курьера'), ('is_operator', 'Разрешения оператора')]},
        ),
    ]
