# Generated by Django 2.1 on 2018-12-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181225_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Готовится'), (2, 'В пути'), (3, 'Доставлен'), (4, 'Отменён')], default=0, verbose_name='Статус'),
        ),
    ]
